// import fetch from 'node-fetch';

// const HF_TOKEN = process.env.HF_TOKEN;
// const HF_MODEL = "meta-llama/Llama-3.1-8B-Instruct";

// export async function getChatCompletion(messages) {
//   try {
//     console.log("🧠 Sending chat to Hugging Face:");
//     console.log(JSON.stringify(messages, null, 2));

//     const response = await fetch("https://api.huggingface.co/chat/completions", {
//       method: "POST",
//       headers: {
//         Authorization: `Bearer ${HF_TOKEN}`,
//         "Content-Type": "application/json",
//       },
//       body: JSON.stringify({
//         model: HF_MODEL,
//         messages: messages,
//         temperature: 0.7,
//         max_tokens: 150,
//       }),
//     });

//     const result = await response.json();

//     if (response.status !== 200) {
//       console.error("❌ Hugging Face API error:", JSON.stringify(result, null, 2));
//       throw new Error(result?.error || "Failed to fetch response from Hugging Face.");
//     }

//     const generated = result.choices?.[0]?.message?.content?.trim();

//     if (!generated) {
//       throw new Error("⚠️ No response generated by model.");
//     }

//     return {
//       choices: [
//         {
//           message: {
//             role: "assistant",
//             content: generated,
//           },
//         },
//       ],
//     };
//   } catch (error) {
//     console.error("❌ getChatCompletion error:", error.message || error);
//     throw error;
//   }
// }
